name: control_env
channels:
  - conda-forge
dependencies:
  - python=3.12
  # common libs
  - tqdm
  - numpy
  - scipy
  - matplotlib
  # graphics libs
  - meshio
  - opencv
  - open3d
  - pyvista
  - pyquaternion
  # sim libs
  - mujoco
  - pinocchio
  - pink
  - pip
  - pip:
    - meshcat
    - meshcat-shapes
    - qpsolvers[open_source_solvers]
    - mink
